apiVersion: v1
kind: ServiceAccount
metadata:
  name: ycsec-readonly-sa
  namespace: ycsec-hardened
  labels:
    app.kubernetes.io/part-of: ycsec
    ycsec.io/profile: hardened
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ycsec-readonly-role
  namespace: ycsec-hardened
  labels:
    app.kubernetes.io/part-of: ycsec
    ycsec.io/profile: hardened
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ycsec-readonly-binding
  namespace: ycsec-hardened
  labels:
    app.kubernetes.io/part-of: ycsec
    ycsec.io/profile: hardened
subjects:
  - kind: ServiceAccount
    name: ycsec-readonly-sa
    namespace: ycsec-hardened
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ycsec-readonly-role
