apiVersion: v1
kind: ServiceAccount
metadata:
  name: ycsec-demo-sa
  namespace: ycsec-hardened
  labels:
    app.kubernetes.io/name: ycsec-demo
    app.kubernetes.io/part-of: ycsec
    ycsec.io/profile: hardened
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ycsec-demo-hardened
  namespace: ycsec-hardened
  labels:
    app.kubernetes.io/name: ycsec-demo
    app.kubernetes.io/part-of: ycsec
    ycsec.io/profile: hardened
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ycsec-demo
      ycsec.io/profile: hardened
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ycsec-demo
        app.kubernetes.io/part-of: ycsec
        ycsec.io/profile: hardened
    spec:
      serviceAccountName: ycsec-demo-sa
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: nginxinc/nginx-unprivileged:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/nginx
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ycsec-demo-hardened
  namespace: ycsec-hardened
  labels:
    app.kubernetes.io/name: ycsec-demo
    app.kubernetes.io/part-of: ycsec
    ycsec.io/profile: hardened
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ycsec-demo
    ycsec.io/profile: hardened
  ports:
    - name: http
      port: 80
      targetPort: 8080
