apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-controlled-app-traffic
  namespace: ycsec-remediated
  labels:
    app.kubernetes.io/name: ycsec-remediated-workload
    security.ycsec.io/control: network-allow-list
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ycsec-remediated-workload
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
