apiVersion: v1
kind: Namespace
metadata:
  name: ycsec-hardened
  labels:
    app.kubernetes.io/part-of: ycsec
    ycsec.io/profile: hardened
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
