apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ycsec-require-readonly-rootfs
  annotations:
    policies.kyverno.io/title: Require read-only root filesystem
    policies.kyverno.io/category: Pod Security
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-readonly-root-filesystem
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Containers must use a read-only root filesystem."
        pattern:
          spec:
            containers:
              - name: "*"
                securityContext:
                  readOnlyRootFilesystem: true
