apiVersion: v1
kind: ServiceAccount
metadata:
  name: hardened-web-sa
  namespace: ycsec-hardened
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hardened-read-pods-role
  namespace: ycsec-hardened
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hardened-read-pods-binding
  namespace: ycsec-hardened
subjects:
  - kind: ServiceAccount
    name: hardened-web-sa
    namespace: ycsec-hardened
roleRef:
  kind: Role
  name: hardened-read-pods-role
  apiGroup: rbac.authorization.k8s.io
