apiVersion: v1
kind: Pod
metadata:
  name: ycsec-hardened-workload-allowed
  namespace: ycsec-admission-validation
  labels:
    app.kubernetes.io/name: ycsec-hardened-workload-allowed
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: hardened
      image: IMAGE_PLACEHOLDER
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: "10m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
