apiVersion: v1
kind: Namespace
metadata:
  name: ycsec-admission-validation
  labels:
    app.kubernetes.io/name: ycsec-admission-validation
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
