apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-web
  namespace: ycsec-insecure-baseline
  labels:
    app: insecure-web
    ycsec.security-state: insecure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-web
  template:
    metadata:
      labels:
        app: insecure-web
        ycsec.security-state: insecure
    spec:
      serviceAccountName: baseline-overprivileged-sa
      automountServiceAccountToken: true
      containers:
        - name: web
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            runAsUser: 0
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: insecure-web
  namespace: ycsec-insecure-baseline
spec:
  type: ClusterIP
  selector:
    app: insecure-web
  ports:
    - name: http
      port: 80
      targetPort: 80
